import { RouterProvider, createRouter } from "@tanstack/react-router";
import { ThemeProvider } from "next-themes";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Toaster } from "sonner";

import { ModalProvider } from "@/providers/modal-provider";
import { QueryProvider } from "@/providers/query-provider";

// Self-hosted fonts (no runtime Google Fonts dependency). These packages ship
// the @font-face declarations; index.css maps them onto the --font-* tokens.
import "@fontsource-variable/inter";
import "@fontsource-variable/lexend";
import "./index.css";

// routeTree.gen.ts is generated by the TanStack Router Vite plugin from the
// files under src/routes. Run `pnpm dev` or `pnpm build` to (re)generate it.
import { routeTree } from "./routeTree.gen";

const router = createRouter({
	routeTree,
	defaultPreload: "intent",
	scrollRestoration: true,
});

// Register the router instance for type-safety across the app (Link `to`,
// useNavigate, search params, etc. all become typed against these routes).
declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router;
	}
}

const rootElement = document.getElementById("root");
if (!rootElement) {
	throw new Error('Root element "#root" was not found in index.html');
}

createRoot(rootElement).render(
	<StrictMode>
		<QueryProvider>
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
				disableTransitionOnChange
			>
				<RouterProvider router={router} />
				<ModalProvider />
				<Toaster richColors />
			</ThemeProvider>
		</QueryProvider>
	</StrictMode>,
);
